# Generated by Django 2.2.16 on 2022-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'user'),
                    ('moderator', 'moderator'),
                    ('admin', 'admin'),
                ],
                default='user',
                max_length=15,
                verbose_name='Роль пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='email'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=False, verbose_name='активированный аккаунт'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150, unique=True, verbose_name='Ник пользователя'
            ),
        ),
    ]
