# Generated by Django 2.2.16 on 2022-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220815_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['-date_joined'],
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(
                blank=True, default=0, max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'Пользователь'),
                    ('moderator', 'Модератор'),
                    ('admin', 'Администратор'),
                ],
                default='user',
                max_length=15,
                verbose_name='Роль пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                db_index=True,
                max_length=150,
                unique=True,
                verbose_name='Ник пользователя',
            ),
        ),
    ]
